name: build-app
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Build
        run: go build -o govh-mrm-linux-amd64 -v ./...
      - name: Publish Release
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        with:
          # upload any assets to your github release
          upload_assets: 'govh-mrm-linux-amd64'
          version_metadata_path: './VERSION'
