name: build-app
on: 
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Build
        run: go build -o govh-mrm-linux-amd64 main.go
      - name: Commit Changes
        id: commit
        uses: packagrio/action-releasr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_email: 'contact@julienvinet.dev'
          author_name: 'Julien Vinet'
      - name: Publish Release
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_assets: 'govh-mrm-linux-amd64'
          author_email: 'contact@julienvinet.dev'
          author_name: 'Julien Vinet'
