name: CI
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.17.3
    env:
      PROJECT_PATH: /go/src/github.com/julienvinet/govh-mrm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p $PROJECT_PATH
          cp -a $GITHUB_WORKSPACE/* $PROJECT_PATH/
          cd $PROJECT_PATH
          go mod vendor
          go build -ldflags "-X main.goos=linux -X main.goarch=amd64" -o govh-mrm-linux-amd64 -tags "static" main.go
          chmod +x govh-mrm-linux-amd64
          .govh-mrm-linux-amd64 --help
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: govh-mrm-binary
          path: ${{ env.PROJECT_PATH }}/govh-mrm-linux-amd64